In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
!pip install catboost -q

In [3]:
from catboost import CatBoostClassifier
import pandas as pd

In [4]:
path = '/content/drive/MyDrive/Study/hackathons/datasecrets_first_cup/'

In [5]:
df_train = pd.read_csv(path + 'data/train_target.csv')
df_train

,ClientUUId,Id,OrderType,LocalBeginDate,LocalEndDate,OrderPrice,Discount,apply_promo
0,000D3A20F23EA95811E7B99F3ED09FC8,7,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,699,200,0
1,000D3A20F23EA95811E7B99F3ED09FC8,6,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1249,25,0
2,000D3A20F23EA95811E7BD373E79565E,5,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,799,200,0
3,000D3A20F23EA95811E7BD373E79565E,5,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1249,250,0
4,000D3A20F23EA95811E7BDAE71CD3F33,6,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,699,30,0
...,...,...,...,...,...,...,...,...
27736,82EDBCD6CE60978F11EDC591DCA75401,5,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,799,200,0
27737,82EDBCD6CE60978F11EDC591DCA75401,5,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1249,250,0
27738,82F78FC7401A9ADD11EDFA15A350D31F,6,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,799,20,0
27739,8606F5E4CA39BF7211EE517E6E1D90B7,5,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,749,200,0
27740,8606F5E4CA39BF7211EE517E6E1D90B7,5,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1249,250,0

In [6]:
df_orders = pd.read_csv(path + 'data/orders.csv')
df_orders

,OrderUUId,addressId,deliverySectorId,ClientUUId,Date,SaleDate,UnitUUId,NewClient,ClientOrderNumber,ProductUUId,CategoryId,ProductTotalPrice,MenuPrice,OrderState,OrderPaymentType,OrderTotalPrice,OrderType,apply_promo
0,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0,18,000D3A240C71BE9A11E719BE2AB264A6,4,1.0,45.0,4,2,1.0,3,0
1,02164D9B0F67BC3311EE610987AF48C7,0.0,0.0,000D3A21DA51A81411EAF10674007D74,2023-10-02,2023-10-02T21:31:32.000Z,000D3A26B5B080DF11E745FD0474B95C,0,29,11EC9AABAD354BE051CCF1EE1F83A8D0,1,485.0,485.0,4,2,1164.0,1,0
2,02164D9B0F67BC3311EE610987AF48C7,0.0,0.0,000D3A21DA51A81411EAF10674007D74,2023-10-02,2023-10-02T21:31:32.000Z,000D3A26B5B080DF11E745FD0474B95C,0,29,11EB846583CB3BDEA80D1A7F2E184D40,1,589.0,589.0,4,2,1164.0,1,0
3,02164D9B0F67BC3311EE610987AF48C7,0.0,0.0,000D3A21DA51A81411EAF10674007D74,2023-10-02,2023-10-02T21:31:32.000Z,000D3A26B5B080DF11E745FD0474B95C,0,29,000D3A240C71BE9A11E719BE2AB267FD,4,45.0,45.0,4,2,1164.0,1,0
4,02164D9B0F67BC3311EE610987AF48C7,0.0,0.0,000D3A21DA51A81411EAF10674007D74,2023-10-02,2023-10-02T21:31:32.000Z,000D3A26B5B080DF11E745FD0474B95C,0,29,000D3A240C71BE9A11E719BE2AB264A6,4,45.0,45.0,4,2,1164.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611734,FEE4A40E62DA936011EE0DA9C66D87C8,0.0,0.0,000D3A39D824A82E11EA2BB7F48841A0,2023-06-18,2023-06-18T15:34:13.000Z,000D3A22FA54A81411E95B9E966DC9B2,0,55,11EA5EE49DCBD9124A66F764872C8E20,1,594.0,719.0,4,2,1509.0,1,0
611735,FEE4A40E62DA936011EE0DA9C66D87C8,0.0,0.0,000D3A39D824A82E11EA2BB7F48841A0,2023-06-18,2023-06-18T15:34:13.000Z,000D3A22FA54A81411E95B9E966DC9B2,0,55,000D3A39D824A82E11E9A18231161F87,1,395.0,479.0,4,2,1509.0,1,0
611736,FEE7759E6F988C7111EDC1BDEEDF6376,9723140.0,4103.0,000D3A22FA54A81411E9BC5EF27EE5BF,2023-03-24,2023-03-24T15:50:51.000Z,000D3A24D2B7A94311E8706B7529EBFD,0,28,000D3A240C71BE9A11E719BE2AB2D427,3,169.0,169.0,4,2,557.0,1,0
611737,FEE7759E6F988C7111EDC1BDEEDF6376,9723140.0,4103.0,000D3A22FA54A81411E9BC5EF27EE5BF,2023-03-24,2023-03-24T15:50:51.000Z,000D3A24D2B7A94311E8706B7529EBFD,0,28,11ED08AA93691DC615EE94EB19CD7070,3,189.0,189.0,4,2,557.0,1,0
611738,FEE7759E6F988C7111EDC1BDEEDF6376,9723140.0,4103.0,000D3A22FA54A81411E9BC5EF27EE5BF,2023-03-24,2023-03-24T15:50:51.000Z,000D3A24D2B7A94311E8706B7529EBFD,0,28,11ED276CA17B3D3016833EF686833390,3,199.0,199.0,4,2,557.0,1,0

In [7]:
print('df_train ClientUUId & df_orders ClientUUId\t', len(set(df_train['ClientUUId']) & set(df_orders['ClientUUId'])))
print('df_train ClientUUId\t\t\t\t', len(set(df_train['ClientUUId'])))
print('df_orders ClientUUId\t\t\t\t', len(set(df_orders['ClientUUId'])))

df_train ClientUUId & df_orders ClientUUId	 10023
df_train ClientUUId				 18598
df_orders ClientUUId				 16337

In [8]:
df_merge = pd.merge(df_orders, df_train, how='outer', on='ClientUUId')
print(df_merge[['apply_promo_x', 'apply_promo_y']].isna().mean())
df_merge

apply_promo_x    0.015549
apply_promo_y    0.287105
dtype: float64

,OrderUUId,addressId,deliverySectorId,ClientUUId,Date,SaleDate,UnitUUId,NewClient,ClientOrderNumber,ProductUUId,...,OrderTotalPrice,OrderType_x,apply_promo_x,Id,OrderType_y,LocalBeginDate,LocalEndDate,OrderPrice,Discount,apply_promo_y
0,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,...,1.0,3.0,0.0,5.0,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,699.0,150.0,0.0
1,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,...,1.0,3.0,0.0,5.0,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1099.0,250.0,0.0
2,7E56F93B9996989111EE287E2FB97BE3,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-07-22,2023-07-22T22:26:45.000Z,000D3A38B306A94411E8924C02E134A4,0.0,20.0,11EBADD4B90B8B4F0F2EF40F8BDAB3D0,...,199.0,2.0,0.0,5.0,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,699.0,150.0,0.0
3,7E56F93B9996989111EE287E2FB97BE3,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-07-22,2023-07-22T22:26:45.000Z,000D3A38B306A94411E8924C02E134A4,0.0,20.0,11EBADD4B90B8B4F0F2EF40F8BDAB3D0,...,199.0,2.0,0.0,5.0,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1099.0,250.0,0.0
4,7E56F93B9996989111EE287E2FB97BE3,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-07-22,2023-07-22T22:26:45.000Z,000D3A38B306A94411E8924C02E134A4,0.0,20.0,11ECB9E3A88791176470AA6E3C42AC80,...,199.0,2.0,0.0,5.0,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,699.0,150.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818106,NaN,NaN,NaN,7E595BF1EB05B56E11EDB9C6FE6B0F7B,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.0,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1249.0,30.0,0.0
818107,NaN,NaN,NaN,7EF11191557BBC0511ED996991D7EAAA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7.0,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,799.0,200.0,0.0
818108,NaN,NaN,NaN,82F78FC7401A9ADD11EDFA15A350D31F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6.0,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,799.0,20.0,0.0
818109,NaN,NaN,NaN,8606F5E4CA39BF7211EE517E6E1D90B7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,"2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,749.0,200.0,0.0
818110,NaN,NaN,NaN,8606F5E4CA39BF7211EE517E6E1D90B7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,"1,2,3",2023-11-02T00:00:00.000Z,2023-11-05T23:59:00.000Z,1249.0,250.0,0.0

In [9]:
df_clients_promo_october = pd.read_csv(path + 'data/clients_promo_october.csv')
df_clients_promo_october

,ClientUUId,Id,LocalBeginDate,LocalEndDate,OrderType,OrderPrice,Discount
0,000D3A20F23EA95811E7B7104AC23CD3,6,2023-10-12T00:00:00.000Z,2023-10-15T23:59:00.000Z,"1,2,3",1299,25
1,000D3A20F23EA95811E7B7D79FAABAA1,5,2023-10-12T00:00:00.000Z,2023-10-15T23:59:00.000Z,"1,2,3",1299,300
2,000D3A20F23EA95811E7B8BD71C73877,7,2023-10-12T00:00:00.000Z,2023-10-15T23:59:00.000Z,"1,2,3",1249,200
3,000D3A20F23EA95811E7B99F3ED09FC8,6,2023-10-12T00:00:00.000Z,2023-10-15T23:59:00.000Z,"1,2,3",1249,30
4,000D3A20F23EA95811E7BD373E79565E,6,2023-10-12T00:00:00.000Z,2023-10-15T23:59:00.000Z,"1,2,3",1299,20
...,...,...,...,...,...,...,...
477270,82EDCEB57826A0A811ED680C33F09E52,6,2023-10-30T00:00:00.000Z,2023-11-01T23:59:00.000Z,"2,3",799,20
477271,82F78FC7401A9ADD11EDFA15A350D31F,5,2023-10-30T00:00:00.000Z,2023-11-01T23:59:00.000Z,"2,3",799,200
477272,82F78FC7401AA4A811EDF992437D8CC6,5,2023-10-30T00:00:00.000Z,2023-11-01T23:59:00.000Z,"2,3",799,200
477273,82F9662CB356B7E011EE167FC961059B,6,2023-10-30T00:00:00.000Z,2023-11-01T23:59:00.000Z,"2,3",799,20
477274,8606F5E4CA39BF7211EE517E6E1D90B7,6,2023-10-30T00:00:00.000Z,2023-11-01T23:59:00.000Z,"2,3",749,25

In [11]:
cols = ['OrderUUId', 'addressId', 'deliverySectorId', 'ClientUUId', 'Date',
       'SaleDate', 'UnitUUId', 'NewClient', 'ClientOrderNumber', 'ProductUUId',
       'CategoryId', 'ProductTotalPrice', 'MenuPrice', 'OrderState',
       'OrderPaymentType', 'OrderTotalPrice', 'OrderType_x', 'apply_promo_x']

cols2rename = {'OrderType_x': 'OrderType',
               'apply_promo_x': 'apply_promo'}

df_merge_promo = pd.merge(df_merge, df_clients_promo_october, how='outer', on='ClientUUId')[cols].rename(columns=cols2rename)

In [12]:
df_merge_promo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13347707 entries, 0 to 13347706
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   OrderUUId          object
 1   addressId          float64
 2   deliverySectorId   float64
 3   ClientUUId         object
 4   Date               object
 5   SaleDate           object
 6   UnitUUId           object
 7   NewClient          float64
 8   ClientOrderNumber  float64
 9   ProductUUId        object
 10  CategoryId         float64
 11  ProductTotalPrice  float64
 12  MenuPrice          float64
 13  OrderState         float64
 14  OrderPaymentType   float64
 15  OrderTotalPrice    float64
 16  OrderType          float64
 17  apply_promo        float64
dtypes: float64(12), object(6)
memory usage: 1.8+ GB

In [14]:
df_merge_promo['apply_promo'].isna().mean()

0.020638376314373697

In [15]:
df_merge_promo = df_merge_promo.dropna(subset=['apply_promo', 'addressId', 'deliverySectorId'])
df_merge_promo

,OrderUUId,addressId,deliverySectorId,ClientUUId,Date,SaleDate,UnitUUId,NewClient,ClientOrderNumber,ProductUUId,CategoryId,ProductTotalPrice,MenuPrice,OrderState,OrderPaymentType,OrderTotalPrice,OrderType,apply_promo
0,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,4.0,1.0,45.0,4.0,2.0,1.0,3.0,0.0
1,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,4.0,1.0,45.0,4.0,2.0,1.0,3.0,0.0
2,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,4.0,1.0,45.0,4.0,2.0,1.0,3.0,0.0
3,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,4.0,1.0,45.0,4.0,2.0,1.0,3.0,0.0
4,020DD76CCD949AE011EDE031ED5D76FD,NaN,NaN,000D3AAC9DCABB2E11EBE0614C89D044,2023-04-21,2023-04-21T20:51:26.000Z,000D3A2480C380DA11E692CFB9F92484,0.0,18.0,000D3A240C71BE9A11E719BE2AB264A6,4.0,1.0,45.0,4.0,2.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13072227,B293BF5C03118D6A11EE6087A48E765C,NaN,NaN,000D3A21DA51A81411EA895AE13DE6B1,2023-10-01,2023-10-01T21:31:02.000Z,000D3A39D824A82E11EA224718607BF4,0.0,12.0,11ECC461B684E7ED07BF221B3A25F280,1.0,276.0,289.0,4.0,2.0,829.0,3.0,0.0
13072228,B293BF5C03118D6A11EE6087A48E765C,NaN,NaN,000D3A21DA51A81411EA895AE13DE6B1,2023-10-01,2023-10-01T21:31:02.000Z,000D3A39D824A82E11EA224718607BF4,0.0,12.0,11ECC461B684E7ED07BF221B3A25F280,1.0,276.0,289.0,4.0,2.0,829.0,3.0,0.0
13072229,B293BF5C03118D6A11EE6087A48E765C,NaN,NaN,000D3A21DA51A81411EA895AE13DE6B1,2023-10-01,2023-10-01T21:31:02.000Z,000D3A39D824A82E11EA224718607BF4,0.0,12.0,11ECC461B684E7ED07BF221B3A25F280,1.0,276.0,289.0,4.0,2.0,829.0,3.0,0.0
13072230,B293BF5C03118D6A11EE6087A48E765C,NaN,NaN,000D3A21DA51A81411EA895AE13DE6B1,2023-10-01,2023-10-01T21:31:02.000Z,000D3A39D824A82E11EA224718607BF4,0.0,12.0,11ECC461B684E7ED07BF221B3A25F280,1.0,276.0,289.0,4.0,2.0,829.0,3.0,0.0
13072231,B293BF5C03118D6A11EE6087A48E765C,NaN,NaN,000D3A21DA51A81411EA895AE13DE6B1,2023-10-01,2023-10-01T21:31:02.000Z,000D3A39D824A82E11EA224718607BF4,0.0,12.0,11ECC461B684E7ED07BF221B3A25F280,1.0,276.0,289.0,4.0,2.0,829.0,3.0,0.0

In [17]:
df_merge_promo.isna().mean()

OrderUUId            0.000000
addressId            0.194027
deliverySectorId     0.194027
ClientUUId           0.000000
Date                 0.000000
SaleDate             0.000000
UnitUUId             0.000000
NewClient            0.000000
ClientOrderNumber    0.000000
ProductUUId          0.000000
CategoryId           0.000000
ProductTotalPrice    0.000000
MenuPrice            0.000000
OrderState           0.000000
OrderPaymentType     0.000000
OrderTotalPrice      0.000000
OrderType            0.000000
apply_promo          0.000000
dtype: float64